# Generated by Django 3.2.12 on 2022-04-02 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='patient/profile_picture/')),
                ('address', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phone_number', models.CharField(max_length=11)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Widower', 'Widower')], max_length=20)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kins_phone_number', models.CharField(max_length=11)),
                ('next_of_kins_email', models.EmailField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
