# Generated by Django 3.2.12 on 2022-04-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctorprofile_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(choices=[('St Maries', 'St Maries'), ('Jos', 'Jos')], default='', max_length=100),
        ),
    ]
