# Generated by Django 3.2.12 on 2022-04-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
    ]
