# Generated by Django 3.2.12 on 2022-04-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_doctorprofile_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='email_address',
        ),
    ]
