# Generated by Django 3.2.12 on 2022-04-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pharmacy_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
