# Generated by Django 3.2.12 on 2022-04-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_doctorprofile_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
