# Generated by Django 3.2.12 on 2022-04-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invoiceitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total',
        ),
    ]
