# Generated by Django 3.2.12 on 2022-04-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_adminprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.CharField(choices=[('Booked', 'Booked'), ('Rescheduled', 'Rescheduled'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], max_length=30)),
                ('appointment_date_time', models.DateTimeField()),
                ('appointment_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctorprofile')),
            ],
        ),
    ]
