# Generated by Django 3.2.12 on 2022-04-06 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Booked', 'Booked'), ('Rescheduled', 'Rescheduled'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], max_length=30),
        ),
    ]
