# Generated by Django 3.2.12 on 2022-04-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220408_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_with',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.doctorprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.patientprofile'),
        ),
    ]
